### ISSUE TITLE
添加用户骚话和趣图

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/author#12]
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/8476969/180244046-59b2ade8-6195-47a2-953a-fb20b576ff67.png">

加上指定用户的骚话 和 趣图。

趣图注意使用cdn链接替换

如果公开的接口没有user_id参数，就自己去cms增加一下支持

给官方过渡阶段查他们的盒币来源用的

**Comment by Kaviilee** [comment]
@iRuxu 待验收
