### ISSUE TITLE
新版个人首页优化

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/author#15]
更多按钮的，展示一个下拉菜单。
分别为：

+ 举报
+ 拉黑

<img width="396" alt="image" src="https://user-images.githubusercontent.com/8476969/197354194-f5d6f9d0-875c-4a25-975e-85d912410772.png">

举报直接跳转值  `/feedback`

拉黑，则参考 https://www.jx3box.com/dashboard/privacy?tab=blacklist 这里添加黑名单的接口即可

- [x] 已完成

**Comment by iRuxu** [comment]
## 海报
<img width="615" alt="image" src="https://user-images.githubusercontent.com/8476969/197354363-a04b7c4a-6b29-4ccb-83f2-1e2f7f3f5b51.png">
https://www.jx3box.com/author/6

这里有些栏目默认的图，是需要指定的地址，具体来说。

macro，bps栏目使用  https://img.jx3box.com/image/bps_thumbnail/10243.png
也就是 __imgPath +     心法id.png

jx3dat栏目使用 https://img.jx3box.com/image/banner/jx3dat1.png
jx3dat + type的值.png

fb栏目使用 https://img.jx3box.com/image/fb_map_thumbnail/573.png
副本地图id.png，怎么实现我忘了，要去看fb库的代码

tool栏目使用https://img.jx3box.com/image/banner/tool1.png
tool + type的值.png

bbs栏目使用 https://img.jx3box.com/image/banner/bbs1.png
bbs + type的值.png

这个最新作品，只包含这6大主栏目目前。

- [x] 已完成

**Comment by nierssaxa** [comment]
![XPKMW3ALV62I0QH~{5IWICK](https://user-images.githubusercontent.com/97571785/197356457-ff73e6b3-5840-4ef8-b134-8990817fd821.png)
关注和更多的按钮严格按照figma的样式来做。
如上图所示，该区域的每项变化都是固定好尺寸的，不接受任何情况下的变动。
其中关注按钮的外发光阴影为 #FF7CAB 透明度40% BlurRadius14 Y4

- [x] 已完成
